"""OpenRouter API client with vision model support."""

import base64
import logging
import time
from pathlib import Path

import requests

logger = logging.getLogger(__name__)

# OpenRouter API endpoint
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Popular vision models on OpenRouter
OPENROUTER_VISION_MODELS = [
    "openai/gpt-4o",
    "openai/gpt-4o-mini",
    "openai/chatgpt-4o-latest",
    "anthropic/claude-sonnet-4",
    "anthropic/claude-3.5-sonnet",
    "google/gemini-2.0-flash-001",
    "google/gemini-pro-vision",
    "qwen/qwen2.5-vl-72b-instruct",
    "qwen/qwen2.5-vl-32b-instruct",
    "qwen/qwen-vl-max",
    "meta-llama/llama-3.2-90b-vision-instruct",
    "meta-llama/llama-3.2-11b-vision-instruct",
]


def get_mime_type(file_path: Path) -> str:
    """Get MIME type based on file extension."""
    ext = file_path.suffix.lower()
    mime_types = {
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.png': 'image/png',
        '.gif': 'image/gif',
        '.webp': 'image/webp',
        '.bmp': 'image/bmp'
    }
    return mime_types.get(ext, 'image/jpeg')


def encode_image_base64(image_path: Path) -> str:
    """Encode an image to base64.

    Args:
        image_path: Path to the image.

    Returns:
        The base64 encoded image.
    """
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def describe_image(
    image_path: Path,
    model: str,
    system_prompt: str,
    api_key: str,
    temperature: float = 0.7,
    max_tokens: int = 500,
) -> str:
    """Generate a description of an image via OpenRouter.

    Args:
        image_path: Path to the image to describe.
        model: Name of the OpenRouter model to use.
        system_prompt: System prompt to guide the description.
        api_key: OpenRouter API key.
        temperature: Temperature for generation.
        max_tokens: Maximum tokens in response.

    Returns:
        The description generated by the model.

    Raises:
        requests.exceptions.RequestException: On API error.
        ValueError: On invalid response.
    """
    logger.debug(f"Encoding image: {image_path.name}")
    encode_start = time.time()

    image_data = encode_image_base64(image_path)
    mime_type = get_mime_type(image_path)
    encode_time = time.time() - encode_start
    logger.debug(f"Image encoded in {encode_time:.2f}s - {len(image_data)} bytes base64")

    # Prepare request
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/hydropix/AutoDescribe-Images",
        "X-Title": "AutoDescribe-Images",
    }

    data = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": system_prompt + "\n\nDescribe this image."
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{mime_type};base64,{image_data}"
                        }
                    }
                ]
            }
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
    }

    logger.info(f"Sending request to OpenRouter model '{model}' for: {image_path.name}")
    api_start = time.time()

    response = requests.post(OPENROUTER_API_URL, headers=headers, json=data, timeout=120)
    response.raise_for_status()

    result = response.json()
    api_time = time.time() - api_start

    if 'choices' not in result or len(result['choices']) == 0:
        raise ValueError(f"Unexpected response format: {result}")

    response_content = result['choices'][0]['message']['content']
    logger.info(f"Response received in {api_time:.2f}s (length: {len(response_content)} chars)")
    logger.debug(f"Response preview: {response_content[:100]}...")

    return response_content


def list_openrouter_models(api_key: str | None = None) -> list[str]:
    """List available OpenRouter vision models.

    Args:
        api_key: OpenRouter API key (optional, uses default list if not provided).

    Returns:
        List of model names.
    """
    if not api_key:
        return OPENROUTER_VISION_MODELS

    try:
        headers = {
            "Authorization": f"Bearer {api_key}",
        }
        response = requests.get(
            "https://openrouter.ai/api/v1/models",
            headers=headers,
            timeout=10
        )
        response.raise_for_status()

        models = response.json().get("data", [])
        # Filter for vision-capable models (those that support images)
        vision_models = []
        for model in models:
            model_id = model.get("id", "")
            # Include models known to support vision or with vision in architecture
            architecture = model.get("architecture", {})
            if architecture.get("modality") == "multimodal" or "vision" in model_id.lower():
                vision_models.append(model_id)

        # If filtering didn't work well, return popular ones
        if len(vision_models) < 5:
            return OPENROUTER_VISION_MODELS

        return sorted(vision_models)

    except Exception as e:
        logger.warning(f"Failed to fetch OpenRouter models: {e}")
        return OPENROUTER_VISION_MODELS
